# Generated by Django 6.0.6 on 2026-06-06 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField(help_text='Calories consumed')),
                ('protein', models.PositiveIntegerField(default=0, help_text='Protein in grams')),
                ('carbs', models.PositiveIntegerField(default=0, help_text='Carbohydrates in grams')),
                ('fat', models.PositiveIntegerField(default=0, help_text='Fat in grams')),
                ('date', models.DateField(help_text='Date when food was eaten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
