# Generated by Django 6.0.6 on 2026-06-11 15:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='time',
            field=models.TimeField(blank=True, help_text='Optional: time of meal (e.g., 08:00 for breakfast)', null=True),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when food was eaten'),
        ),
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['user', 'date'], name='food_fooden_user_id_720367_idx'),
        ),
    ]
