# Generated by Django 6.0.6 on 2026-06-11 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodentry_time_alter_foodentry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], default='lunch', help_text='Which meal this food belongs to (breakfast, lunch, snacks, dinner)', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='time',
            field=models.TimeField(blank=True, help_text='Optional: exact time of meal (e.g., 08:00 for breakfast)', null=True),
        ),
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['user', 'meal_type'], name='food_fooden_user_id_460897_idx'),
        ),
    ]
