# Generated by Django 6.0.6 on 2026-06-11 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_sets', models.PositiveSmallIntegerField(default=3)),
                ('default_reps', models.PositiveSmallIntegerField(default=10)),
                ('default_duration_seconds', models.PositiveSmallIntegerField(blank=True, help_text='For timed exercises like Plank', null=True)),
                ('muscle_group', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('exercises_count', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target number (e.g. 4 workouts)', max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='workouts', help_text='e.g. workouts, km, push-ups', max_length=20)),
                ('period_days', models.PositiveSmallIntegerField(default=7, help_text='Goal period in days (e.g. weekly goal = 7)')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('achieved', 'Achieved')], default='not_started', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.PositiveSmallIntegerField(default=10)),
                ('duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Sets, reps, intensity, etc.'),
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='time',
            field=models.TimeField(blank=True, help_text='Optional: time of workout', null=True),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of workout'),
        ),
        migrations.AddIndex(
            model_name='workoutentry',
            index=models.Index(fields=['user', 'date'], name='workouts_wo_user_id_b3525e_idx'),
        ),
        migrations.AddField(
            model_name='scheduledworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutplan'),
        ),
        migrations.AddIndex(
            model_name='scheduledworkout',
            index=models.Index(fields=['user', 'scheduled_date', 'completed'], name='workouts_sc_user_id_979b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutplanexercise',
            unique_together={('workout_plan', 'exercise')},
        ),
    ]
